// CameraKit.framework umbrella header
// Auto-generated from iOS 8.4.3 dyld_shared_cache (AppleTV 3,2)

#import <Foundation/Foundation.h>

#import <CameraKit/CAMAnimationDelegate.h>
#import <CameraKit/CAMAnimationHelper.h>
#import <CameraKit/CAMApplicationSpec.h>
#import <CameraKit/CAMApplicationViewController.h>
#import <CameraKit/CAMAssetSaver.h>
#import <CameraKit/CAMAvalanche.h>
#import <CameraKit/CAMAvalancheCaptureService.h>
#import <CameraKit/CAMAvalancheIndicatorView.h>
#import <CameraKit/CAMAvalancheSession.h>
#import <CameraKit/CAMBadgeTextView.h>
#import <CameraKit/CAMBadgeView.h>
#import <CameraKit/CAMBlurredSnapshotView.h>
#import <CameraKit/CAMBottomBar.h>
#import <CameraKit/CAMButtonLabel.h>
#import <CameraKit/CAMCameraRoll.h>
#import <CameraKit/CAMCameraRollSpec.h>
#import <CameraKit/CAMCameraSpec.h>
#import <CameraKit/CAMCameraView.h>
#import <CameraKit/CAMCameraViewController.h>
#import <CameraKit/CAMCaptureController.h>
#import <CameraKit/CAMCaptureRequest.h>
#import <CameraKit/CAMCaptureResponse.h>
#import <CameraKit/CAMCaptureService.h>
#import <CameraKit/CAMCaptureSessionConfigurationOptions.h>
#import <CameraKit/CAMDebugCaptureService.h>
#import <CameraKit/CAMDisabledModeOverlayView.h>
#import <CameraKit/CAMEffectFilterManager.h>
#import <CameraKit/CAMEffectPreviewView.h>
#import <CameraKit/CAMEffectSelectionViewController.h>
#import <CameraKit/CAMEffectSelectionViewControllerView.h>
#import <CameraKit/CAMEffectsFullsizeView.h>
#import <CameraKit/CAMEffectsGridLabelsView.h>
#import <CameraKit/CAMEffectsGridView.h>
#import <CameraKit/CAMEffectsRenderer.h>
#import <CameraKit/CAMElapsedTimeView.h>
#import <CameraKit/CAMExpandableMenuButton.h>
#import <CameraKit/CAMExposureBiasSlider.h>
#import <CameraKit/CAMExposureBiasSliderThumb.h>
#import <CameraKit/CAMExposureBiasTextView.h>
#import <CameraKit/CAMFaceTrackingView.h>
#import <CameraKit/CAMFilterButton.h>
#import <CameraKit/CAMFlashBadge.h>
#import <CameraKit/CAMFlashButton.h>
#import <CameraKit/CAMFlipButton.h>
#import <CameraKit/CAMFocusAttachmentView.h>
#import <CameraKit/CAMFocusLockAttachmentView.h>
#import <CameraKit/CAMFocusLockView.h>
#import <CameraKit/CAMFocusPointView.h>
#import <CameraKit/CAMFocusSplitAttachmentView.h>
#import <CameraKit/CAMFocusView.h>
#import <CameraKit/CAMFormattingManager.h>
#import <CameraKit/CAMGLView.h>
#import <CameraKit/CAMGridView.h>
#import <CameraKit/CAMHDRBadge.h>
#import <CameraKit/CAMHDRButton.h>
#import <CameraKit/CAMHardwareLockIndicatorView.h>
#import <CameraKit/CAMImagePickerSpec.h>
#import <CameraKit/CAMImageWell.h>
#import <CameraKit/CAMInflightAsset.h>
#import <CameraKit/CAMKeepDaemonAliveAssertion.h>
#import <CameraKit/CAMLegibilityViewHelper.h>
#import <CameraKit/CAMLocationCaptureService.h>
#import <CameraKit/CAMLocationController.h>
#import <CameraKit/CAMLowDiskSpaceAlertView.h>
#import <CameraKit/CAMModeDial.h>
#import <CameraKit/CAMModeDialItem.h>
#import <CameraKit/CAMMotionController.h>
#import <CameraKit/CAMMutablePanoramaCaptureRequest.h>
#import <CameraKit/CAMMutableStillImageCaptureRequest.h>
#import <CameraKit/CAMMutableVideoCaptureRequest.h>
#import <CameraKit/CAMNebulaDaemonProxyManager.h>
#import <CameraKit/CAMNebulaSecondaryState.h>
#import <CameraKit/CAMNebulaUtilities.h>
#import <CameraKit/CAMPadApplicationSpec.h>
#import <CameraKit/CAMPadImagePickerSpec.h>
#import <CameraKit/CAMPanoramaArrowView.h>
#import <CameraKit/CAMPanoramaCaptureParameters.h>
#import <CameraKit/CAMPanoramaCaptureRequest.h>
#import <CameraKit/CAMPanoramaLabel.h>
#import <CameraKit/CAMPanoramaLevelView.h>
#import <CameraKit/CAMPanoramaView.h>
#import <CameraKit/CAMPhoneApplicationSpec.h>
#import <CameraKit/CAMPhoneImagePickerSpec.h>
#import <CameraKit/CAMPhysicalCaptureRecognizer.h>
#import <CameraKit/CAMPreviewView.h>
#import <CameraKit/CAMSecureWindow.h>
#import <CameraKit/CAMShutterButton.h>
#import <CameraKit/CAMShutterIndicatorView.h>
#import <CameraKit/CAMSlalomIndicatorView.h>
#import <CameraKit/CAMStillImageCaptureRequest.h>
#import <CameraKit/CAMStillImageCaptureResponse.h>
#import <CameraKit/CAMTimelapseBackendController.h>
#import <CameraKit/CAMTimelapseBackendSessionContext.h>
#import <CameraKit/CAMTimelapseController.h>
#import <CameraKit/CAMTimelapseDiskUtilities.h>
#import <CameraKit/CAMTimelapseJPEGReader.h>
#import <CameraKit/CAMTimelapseMovieWriter.h>
#import <CameraKit/CAMTimelapseSettings.h>
#import <CameraKit/CAMTimelapseShutterRingView.h>
#import <CameraKit/CAMTimelapseState.h>
#import <CameraKit/CAMTimerButton.h>
#import <CameraKit/CAMTimerIndicatorView.h>
#import <CameraKit/CAMTopBar.h>
#import <CameraKit/CAMTorchPattern.h>
#import <CameraKit/CAMTorchPatternController.h>
#import <CameraKit/CAMVideoCaptureRequest.h>
#import <CameraKit/CAMVideoCaptureResponse.h>
#import <CameraKit/CAMVideoPreviewView.h>
#import <CameraKit/CAMZoomSlider.h>
#import <CameraKit/DeferredCAMCameraRollSpec.h>
#import <CameraKit/DeferredFrameworkLoader.h>
#import <CameraKit/DeferredPUCameraApplicationViewController.h>
#import <CameraKit/PLCameraIrisAnimationView.h>
#import <CameraKit/PLGLLayerDelegate.h>
#import <CameraKit/PLPreviewOverlayView.h>
