// CoreFoundation.framework umbrella header
// Auto-generated from iOS 8.4.3 dyld_shared_cache (AppleTV 3,2)

#import <Foundation/Foundation.h>

#import <CoreFoundation/CFPDCFDataBuffer.h>
#import <CoreFoundation/CFPDContainerSource.h>
#import <CoreFoundation/CFPDDataBuffer.h>
#import <CoreFoundation/CFPDMMAPBuffer.h>
#import <CoreFoundation/CFPDPurgeableBuffer.h>
#import <CoreFoundation/CFPDSource.h>
#import <CoreFoundation/CFPrefsDirectSource.h>
#import <CoreFoundation/CFPrefsManagedSource.h>
#import <CoreFoundation/CFPrefsPlistSource.h>
#import <CoreFoundation/CFPrefsSearchListSource.h>
#import <CoreFoundation/CFPrefsSource.h>
#import <CoreFoundation/NSArray.h>
#import <CoreFoundation/NSBlock.h>
#import <CoreFoundation/NSBlockInvocation.h>
#import <CoreFoundation/NSCache.h>
#import <CoreFoundation/NSCalendar.h>
#import <CoreFoundation/NSData.h>
#import <CoreFoundation/NSDate.h>
#import <CoreFoundation/NSDateComponents.h>
#import <CoreFoundation/NSDictionary.h>
#import <CoreFoundation/NSEnumerator.h>
#import <CoreFoundation/NSException.h>
#import <CoreFoundation/NSFileSecurity.h>
#import <CoreFoundation/NSInputStream.h>
#import <CoreFoundation/NSInvocation.h>
#import <CoreFoundation/NSLocale.h>
#import <CoreFoundation/NSMethodSignature.h>
#import <CoreFoundation/NSMutableArray.h>
#import <CoreFoundation/NSMutableData.h>
#import <CoreFoundation/NSMutableDictionary.h>
#import <CoreFoundation/NSMutableOrderedSet.h>
#import <CoreFoundation/NSMutableSet.h>
#import <CoreFoundation/NSNull.h>
#import <CoreFoundation/NSOrderedSet.h>
#import <CoreFoundation/NSOutputStream.h>
#import <CoreFoundation/NSRunLoop.h>
#import <CoreFoundation/NSSet.h>
#import <CoreFoundation/NSSharedKeyDictionary.h>
#import <CoreFoundation/NSSharedKeySet.h>
#import <CoreFoundation/NSStream.h>
#import <CoreFoundation/NSStringROMKeySet_Embedded.h>
#import <CoreFoundation/NSTimeZone.h>
#import <CoreFoundation/NSTimer.h>
#import <CoreFoundation/NSURL.h>
#import <CoreFoundation/NSUserDefaults.h>
#import <CoreFoundation/_CFPrefsSynchronizer.h>
#import <CoreFoundation/_CFStreamDelegate.h>
#import <CoreFoundation/_NSChineseBigramKeySet.h>
#import <CoreFoundation/_NSChineseBigramKeySet_SKS.h>
#import <CoreFoundation/_NSChineseBigramKeySet_SKS_SKS.h>
#import <CoreFoundation/_NSCopyOnWriteCalendarWrapper.h>
#import <CoreFoundation/_NSJapaneseBigramKeySet.h>
#import <CoreFoundation/_NSKoreanBigramKeySet.h>
#import <CoreFoundation/_NSKoreanBigramKeySet_SKS.h>
#import <CoreFoundation/_NSMostCommonChineseCharsKeySet.h>
#import <CoreFoundation/_NSMostCommonJapaneseCharsKeySet.h>
#import <CoreFoundation/_NSMostCommonKoreanCharsKeySet.h>
#import <CoreFoundation/_NSPlaceholderLocale.h>
#import <CoreFoundation/_NSRefcountedPthreadMutex.h>
#import <CoreFoundation/_NSSharedKeySetS.h>
#import <CoreFoundation/_NSZombie_.h>
