// CoreHAP.framework umbrella header
// Auto-generated from iOS 8.4.3 dyld_shared_cache (AppleTV 3,2)

#import <Foundation/Foundation.h>

#import <CoreHAP/HAPAccessory.h>
#import <CoreHAP/HAPAccessoryServer.h>
#import <CoreHAP/HAPAccessoryServerBTLE.h>
#import <CoreHAP/HAPAccessoryServerBrowser.h>
#import <CoreHAP/HAPAccessoryServerBrowserBTLE.h>
#import <CoreHAP/HAPAccessoryServerBrowserIP.h>
#import <CoreHAP/HAPAccessoryServerBrowserRelay.h>
#import <CoreHAP/HAPAccessoryServerBrowserWiProxBTLE.h>
#import <CoreHAP/HAPAccessoryServerIP.h>
#import <CoreHAP/HAPAccessoryServerRelay.h>
#import <CoreHAP/HAPAddRemovePairingOperation.h>
#import <CoreHAP/HAPBLEPeripheral.h>
#import <CoreHAP/HAPBTLECharacteristicSignature.h>
#import <CoreHAP/HAPBTLEConnectionRequestTuple.h>
#import <CoreHAP/HAPBTLEControlOutputStream.h>
#import <CoreHAP/HAPBTLEControlPacket.h>
#import <CoreHAP/HAPBTLEReachabilityScanTuple.h>
#import <CoreHAP/HAPBTLERequest.h>
#import <CoreHAP/HAPBTLEResponse.h>
#import <CoreHAP/HAPBTLETransactionIdentifier.h>
#import <CoreHAP/HAPBlockOperation.h>
#import <CoreHAP/HAPBridgedAccessory.h>
#import <CoreHAP/HAPCharacteristic.h>
#import <CoreHAP/HAPCharacteristicEnableEventCompletionTuple.h>
#import <CoreHAP/HAPCharacteristicMetadata.h>
#import <CoreHAP/HAPCharacteristicReadCompletionTuple.h>
#import <CoreHAP/HAPCharacteristicResponseTuple.h>
#import <CoreHAP/HAPCharacteristicWriteRequestTuple.h>
#import <CoreHAP/HAPDataValueTransformer.h>
#import <CoreHAP/HAPDiscoveredBTLEAccessoryServerTuple.h>
#import <CoreHAP/HAPExponentialBackoffTimer.h>
#import <CoreHAP/HAPFragmentationPacket.h>
#import <CoreHAP/HAPFragmentationStream.h>
#import <CoreHAP/HAPHTTPClient.h>
#import <CoreHAP/HAPJSONValueTransformer.h>
#import <CoreHAP/HAPKeychainItem.h>
#import <CoreHAP/HAPMetadata.h>
#import <CoreHAP/HAPMetadataCharacteristic.h>
#import <CoreHAP/HAPMetadataCharacteristicValue.h>
#import <CoreHAP/HAPMetadataConstraints.h>
#import <CoreHAP/HAPMetadataProperty.h>
#import <CoreHAP/HAPMetadataService.h>
#import <CoreHAP/HAPMetadataTuple.h>
#import <CoreHAP/HAPMetadataUnit.h>
#import <CoreHAP/HAPOSTransaction.h>
#import <CoreHAP/HAPPairSetupSession.h>
#import <CoreHAP/HAPPairingIdentity.h>
#import <CoreHAP/HAPPairingKey.h>
#import <CoreHAP/HAPRecentlySeenPairedBTLEPeripheralTuple.h>
#import <CoreHAP/HAPRelayAccessory.h>
#import <CoreHAP/HAPRelayActivationClient.h>
#import <CoreHAP/HAPRelayPairingClient.h>
#import <CoreHAP/HAPRelayRequestMessage.h>
#import <CoreHAP/HAPRelayResponseMessage.h>
#import <CoreHAP/HAPRelayStream.h>
#import <CoreHAP/HAPRemoteSession.h>
#import <CoreHAP/HAPSecuritySession.h>
#import <CoreHAP/HAPService.h>
#import <CoreHAP/HAPSystemKeychainStore.h>
#import <CoreHAP/HAPTimedBlockedOperation.h>
#import <CoreHAP/HAPTimer.h>
#import <CoreHAP/HAPTunneledAccessoryBTLE.h>
#import <CoreHAP/HAPValueTransformer.h>
#import <CoreHAP/HMUIndent.h>
#import <CoreHAP/WLOTcpConnection.h>
#import <CoreHAP/WLOTcpServer.h>
#import <CoreHAP/_HAPAccessoryServerBTLE100.h>
#import <CoreHAP/_HAPAccessoryServerBTLE200.h>
#import <CoreHAP/_HAPBTLEDiscoveryContext.h>
