// Preferences.framework umbrella header
// Auto-generated from iOS 8.4.3 dyld_shared_cache (AppleTV 3,2)

#import <Foundation/Foundation.h>

#import <Preferences/AlphanumericPINTableViewCell.h>
#import <Preferences/AlphanumericPINTextField.h>
#import <Preferences/AlphanumericPINView.h>
#import <Preferences/DevicePINController.h>
#import <Preferences/DevicePINKeypad.h>
#import <Preferences/DevicePINPane.h>
#import <Preferences/DevicePINSetupController.h>
#import <Preferences/DiagnosticDataController.h>
#import <Preferences/DiscreteSlider.h>
#import <Preferences/FailureBarView.h>
#import <Preferences/FontSizeSliderCell.h>
#import <Preferences/KeychainSyncAdvancedSecurityCodeController.h>
#import <Preferences/KeychainSyncAppleSupportController.h>
#import <Preferences/KeychainSyncCountryInfo.h>
#import <Preferences/KeychainSyncDevicePINController.h>
#import <Preferences/KeychainSyncHeaderView.h>
#import <Preferences/KeychainSyncPhoneNumberController.h>
#import <Preferences/KeychainSyncPhoneSettingsFragment.h>
#import <Preferences/KeychainSyncSMSVerificationController.h>
#import <Preferences/KeychainSyncSecurityCodeCell.h>
#import <Preferences/KeychainSyncSecurityCodeController.h>
#import <Preferences/KeychainSyncSetupController.h>
#import <Preferences/KeychainSyncTextEntryController.h>
#import <Preferences/NumericPINView.h>
#import <Preferences/PINView.h>
#import <Preferences/PSAboutHTMLSheetViewController.h>
#import <Preferences/PSAboutTextSheetViewController.h>
#import <Preferences/PSAccessibilitySettingsDetail.h>
#import <Preferences/PSAccountSecurityController.h>
#import <Preferences/PSAdvancedLanguageController.h>
#import <Preferences/PSAdvancedLocaleController.h>
#import <Preferences/PSAirplaneModeSettingsDetail.h>
#import <Preferences/PSAppListController.h>
#import <Preferences/PSAssistiveTouchSettingsDetail.h>
#import <Preferences/PSAutoLockSettingsDetail.h>
#import <Preferences/PSBadgedTableCell.h>
#import <Preferences/PSBarButtonSpinnerView.h>
#import <Preferences/PSBiometricIdentity.h>
#import <Preferences/PSBluetoothSettingsDetail.h>
#import <Preferences/PSBrightnessController.h>
#import <Preferences/PSBrightnessSettingsDetail.h>
#import <Preferences/PSBundleController.h>
#import <Preferences/PSCastleSettingsDetail.h>
#import <Preferences/PSCellularDataSettingsDetail.h>
#import <Preferences/PSClearBackgroundCell.h>
#import <Preferences/PSCloudStorageOffersManager.h>
#import <Preferences/PSCloudStorageQuotaManager.h>
#import <Preferences/PSCompassSettingsDetail.h>
#import <Preferences/PSConfirmationSpecifier.h>
#import <Preferences/PSControlCenterSettingsDetail.h>
#import <Preferences/PSControlTableCell.h>
#import <Preferences/PSDNDSettingsDetail.h>
#import <Preferences/PSDUETSettingsDetail.h>
#import <Preferences/PSDetailController.h>
#import <Preferences/PSEditableListController.h>
#import <Preferences/PSEditableTableCell.h>
#import <Preferences/PSEditingPane.h>
#import <Preferences/PSExpandableAppListGroupController.h>
#import <Preferences/PSExpandableListGroupController.h>
#import <Preferences/PSFaceTimeSettingsDetail.h>
#import <Preferences/PSFacebookSettingsDetail.h>
#import <Preferences/PSFlickrSettingsDetail.h>
#import <Preferences/PSFooterHyperlinkView.h>
#import <Preferences/PSGameCenterSettingsDetail.h>
#import <Preferences/PSGuidedAccessSettingsDetail.h>
#import <Preferences/PSIconMarginTableCell.h>
#import <Preferences/PSInternationalController.h>
#import <Preferences/PSInternationalLanguageController.h>
#import <Preferences/PSInternationalLanguageSetupController.h>
#import <Preferences/PSInternationalStatistics.h>
#import <Preferences/PSInvertColorsSettingsDetail.h>
#import <Preferences/PSKeyboardSettingsDetail.h>
#import <Preferences/PSKeychainSyncManager.h>
#import <Preferences/PSKeychainSyncPhoneNumber.h>
#import <Preferences/PSKeychainSyncViewController.h>
#import <Preferences/PSLanguage.h>
#import <Preferences/PSLanguageSelector.h>
#import <Preferences/PSLanguageTableViewCell.h>
#import <Preferences/PSLargeTextController.h>
#import <Preferences/PSLazyImagePromise.h>
#import <Preferences/PSLegalMessagePane.h>
#import <Preferences/PSListController.h>
#import <Preferences/PSListItemsController.h>
#import <Preferences/PSLocaleController.h>
#import <Preferences/PSLocaleSelector.h>
#import <Preferences/PSLocationServicesSettingsDetail.h>
#import <Preferences/PSMCCSettingsDetail.h>
#import <Preferences/PSMagnifyController.h>
#import <Preferences/PSMagnifyMode.h>
#import <Preferences/PSMapsSettingsDetail.h>
#import <Preferences/PSMessagesSettingsDetail.h>
#import <Preferences/PSMusicSettingsDetail.h>
#import <Preferences/PSNavBarSpinnerManager.h>
#import <Preferences/PSNonMovableTapGestureRecognizer.h>
#import <Preferences/PSNotesSettingsDetail.h>
#import <Preferences/PSNotificationSettingsDetail.h>
#import <Preferences/PSPasscodeField.h>
#import <Preferences/PSPasscodeSettingsDetail.h>
#import <Preferences/PSPhoneNumberSpecifier.h>
#import <Preferences/PSPhoneNumberTableCell.h>
#import <Preferences/PSPhoneSettingsDetail.h>
#import <Preferences/PSPhotosAndCameraSettingsDetail.h>
#import <Preferences/PSPowerlogListController.h>
#import <Preferences/PSPrivacySettingsDetail.h>
#import <Preferences/PSQuotaInfo.h>
#import <Preferences/PSRegion.h>
#import <Preferences/PSRemindersSettingsDetail.h>
#import <Preferences/PSRestrictionsController.h>
#import <Preferences/PSRestrictionsPasscodeController.h>
#import <Preferences/PSRootController.h>
#import <Preferences/PSSafariSettingsDetail.h>
#import <Preferences/PSSearchController.h>
#import <Preferences/PSSearchEntry.h>
#import <Preferences/PSSearchIndexOperation.h>
#import <Preferences/PSSearchModel.h>
#import <Preferences/PSSearchOperation.h>
#import <Preferences/PSSearchResults.h>
#import <Preferences/PSSearchResultsCell.h>
#import <Preferences/PSSearchResultsSwitchCell.h>
#import <Preferences/PSSegmentTableCell.h>
#import <Preferences/PSSegmentableSlider.h>
#import <Preferences/PSSettingsFunctions.h>
#import <Preferences/PSSetupController.h>
#import <Preferences/PSSinaWeiboSettingsDetail.h>
#import <Preferences/PSSiriSettingsDetail.h>
#import <Preferences/PSSliderTableCell.h>
#import <Preferences/PSSoftwareUpdateAnimatedIcon.h>
#import <Preferences/PSSoftwareUpdateReleaseNotesDetail.h>
#import <Preferences/PSSoftwareUpdateTableView.h>
#import <Preferences/PSSoftwareUpdateTitleCell.h>
#import <Preferences/PSSoundsSettingsDetail.h>
#import <Preferences/PSSpecifier.h>
#import <Preferences/PSSpecifierAction.h>
#import <Preferences/PSSpecifierDataSource.h>
#import <Preferences/PSSpecifierGroupIndex.h>
#import <Preferences/PSSpecifierUpdateContext.h>
#import <Preferences/PSSpecifierUpdateOperation.h>
#import <Preferences/PSSpecifierUpdates.h>
#import <Preferences/PSSpinnerTableCell.h>
#import <Preferences/PSSplitViewController.h>
#import <Preferences/PSStackPushAnimationController.h>
#import <Preferences/PSStoreSettingsDetail.h>
#import <Preferences/PSSubtitleSwitchTableCell.h>
#import <Preferences/PSSwitchTableCell.h>
#import <Preferences/PSSystemConfiguration.h>
#import <Preferences/PSSystemConfigurationDynamicStoreMISWatcher.h>
#import <Preferences/PSSystemConfigurationDynamicStoreWifiWatcher.h>
#import <Preferences/PSSystemPolicyForApp.h>
#import <Preferences/PSSystemPolicyManager.h>
#import <Preferences/PSTableCell.h>
#import <Preferences/PSTableCellHighlightContext.h>
#import <Preferences/PSTencentWeiboSettingsDetail.h>
#import <Preferences/PSTextEditingCell.h>
#import <Preferences/PSTextEditingPane.h>
#import <Preferences/PSTextFieldSpecifier.h>
#import <Preferences/PSTextSizeSettingsDetail.h>
#import <Preferences/PSTextView.h>
#import <Preferences/PSTextViewPane.h>
#import <Preferences/PSTextViewTableCell.h>
#import <Preferences/PSThirdPartySettingsDetail.h>
#import <Preferences/PSTorchSettingsDetail.h>
#import <Preferences/PSTwitterSettingsDetail.h>
#import <Preferences/PSUsageBundleApp.h>
#import <Preferences/PSUsageBundleCategory.h>
#import <Preferences/PSUsageBundleCell.h>
#import <Preferences/PSUsageBundleDetailController.h>
#import <Preferences/PSUsageBundleManager.h>
#import <Preferences/PSUsageSizeHeader.h>
#import <Preferences/PSVideosSettingsDetail.h>
#import <Preferences/PSViewController.h>
#import <Preferences/PSVimeoSettingsDetail.h>
#import <Preferences/PSVoiceOverSettingsDetail.h>
#import <Preferences/PSWeakReference.h>
#import <Preferences/PSWebContainerView.h>
#import <Preferences/PSWiFiSettingsDetail.h>
#import <Preferences/PasscodeFieldCell.h>
#import <Preferences/PopBackListItemsController.h>
#import <Preferences/PrefsUILinkLabel.h>
#import <Preferences/ProblemReportingAboutController.h>
#import <Preferences/ProblemReportingController.h>
#import <Preferences/QuietHoursStateController.h>
#import <Preferences/RegionFormatSampleView.h>
#import <Preferences/SuggestedAppsController.h>
#import <Preferences/_PSDeferredUpdates.h>
#import <Preferences/_PSDeleteButtonCell.h>
