/* Runtime dump - CHDTitle
 * Image: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@interface CHDTitle : NSObject
{
    CHDChart * mChart;
    BOOL mIsAutoGenerated;
    BOOL mPositionAutoGenerated;
    BOOL mSizeAutoGenerated;
    CHDFormula * mName;
    EDString * mLastCachedName;
    OADGraphicProperties * mGraphicProperties;
    double mRotation;
}

- (void)dealloc;
- (void)setName:(NSString *)arg0;
- (NSString *)name;
- (NSDictionary *)graphicProperties;
- (NSString *)lastCachedName;
- (CHDTitle *)initWithChart:(GQHChart *)arg0;
- (void)setGraphicProperties:(NSDictionary *)arg0;
- (void)setIsAutoGenerated:(BOOL)arg0;
- (void)setLastCachedName:(NSString *)arg0;
- (void)setIsPositionAutoGenerated:(BOOL)arg0;
- (void)setTitleRotationAngle:(double)arg0;
- (BOOL)isSizeAutoGenerated;
- (BOOL)isCachedTitleEmpty;
- (BOOL)isAutoGenerated;
- (BOOL)isPositionAutoGenerated;
- (void)setIsSizeAutoGenerated:(BOOL)arg0;
- (BOOL)isTitleVisible;
- (double)titleRotationAngle;

@end
