// Metal.framework umbrella header
// Auto-generated from iOS 8.4.3 dyld_shared_cache (AppleTV 3,2)

#import <Foundation/Foundation.h>

#import <Metal/MTLArgument.h>
#import <Metal/MTLArrayType.h>
#import <Metal/MTLBlitCommandEncoder.h>
#import <Metal/MTLBufferArgument.h>
#import <Metal/MTLBuiltInArgument.h>
#import <Metal/MTLCompileOptions.h>
#import <Metal/MTLCompiler.h>
#import <Metal/MTLComputePipelineDescriptor.h>
#import <Metal/MTLComputePipelineReflection.h>
#import <Metal/MTLDebugBlitCommandEncoder.h>
#import <Metal/MTLDebugBuffer.h>
#import <Metal/MTLDebugCommandBuffer.h>
#import <Metal/MTLDebugCommandQueue.h>
#import <Metal/MTLDebugComputeCommandEncoder.h>
#import <Metal/MTLDebugComputePipelineState.h>
#import <Metal/MTLDebugDepthStencilState.h>
#import <Metal/MTLDebugDevice.h>
#import <Metal/MTLDebugFunction.h>
#import <Metal/MTLDebugFunctionArgument.h>
#import <Metal/MTLDebugLibrary.h>
#import <Metal/MTLDebugParallelRenderCommandEncoder.h>
#import <Metal/MTLDebugRenderCommandEncoder.h>
#import <Metal/MTLDebugRenderPipelineState.h>
#import <Metal/MTLDebugSamplerState.h>
#import <Metal/MTLDebugTexture.h>
#import <Metal/MTLDepthStencilDescriptor.h>
#import <Metal/MTLError.h>
#import <Metal/MTLIOAccelBuffer.h>
#import <Metal/MTLIOAccelCommandBuffer.h>
#import <Metal/MTLIOAccelCommandEncoder.h>
#import <Metal/MTLIOAccelCommandQueue.h>
#import <Metal/MTLIOAccelDebugCommandEncoder.h>
#import <Metal/MTLIOAccelDevice.h>
#import <Metal/MTLIOAccelDeviceShmem.h>
#import <Metal/MTLIOAccelDeviceShmemPool.h>
#import <Metal/MTLIOAccelParallelRenderCommandEncoder.h>
#import <Metal/MTLIOAccelPooledResource.h>
#import <Metal/MTLIOAccelRenderCommandEncoder.h>
#import <Metal/MTLIOAccelResource.h>
#import <Metal/MTLIOAccelResourceAllocation.h>
#import <Metal/MTLIOAccelResourcePool.h>
#import <Metal/MTLIOAccelTexture.h>
#import <Metal/MTLIOMemoryInfo.h>
#import <Metal/MTLRenderPassAttachmentDescriptor.h>
#import <Metal/MTLRenderPassColorAttachmentDescriptor.h>
#import <Metal/MTLRenderPassColorAttachmentDescriptorArray.h>
#import <Metal/MTLRenderPassDepthAttachmentDescriptor.h>
#import <Metal/MTLRenderPassDescriptor.h>
#import <Metal/MTLRenderPassStencilAttachmentDescriptor.h>
#import <Metal/MTLRenderPipelineColorAttachmentDescriptor.h>
#import <Metal/MTLRenderPipelineColorAttachmentDescriptorArray.h>
#import <Metal/MTLRenderPipelineDescriptor.h>
#import <Metal/MTLRenderPipelineReflection.h>
#import <Metal/MTLResourceAllocationInfo.h>
#import <Metal/MTLResourceList.h>
#import <Metal/MTLResourceListPool.h>
#import <Metal/MTLSamplerDescriptor.h>
#import <Metal/MTLStencilDescriptor.h>
#import <Metal/MTLStructMember.h>
#import <Metal/MTLStructType.h>
#import <Metal/MTLTextureArgument.h>
#import <Metal/MTLTextureDescriptor.h>
#import <Metal/MTLThreadgroupMemoryArgument.h>
#import <Metal/MTLToolsBlitCommandEncoder.h>
#import <Metal/MTLToolsBuffer.h>
#import <Metal/MTLToolsCommandBuffer.h>
#import <Metal/MTLToolsCommandEncoder.h>
#import <Metal/MTLToolsCommandQueue.h>
#import <Metal/MTLToolsComputeCommandEncoder.h>
#import <Metal/MTLToolsComputePipelineState.h>
#import <Metal/MTLToolsDepthStencilState.h>
#import <Metal/MTLToolsDevice.h>
#import <Metal/MTLToolsFunction.h>
#import <Metal/MTLToolsLibrary.h>
#import <Metal/MTLToolsObject.h>
#import <Metal/MTLToolsParallelRenderCommandEncoder.h>
#import <Metal/MTLToolsPointerArray.h>
#import <Metal/MTLToolsRenderCommandEncoder.h>
#import <Metal/MTLToolsRenderPipelineState.h>
#import <Metal/MTLToolsResource.h>
#import <Metal/MTLToolsSamplerState.h>
#import <Metal/MTLToolsTexture.h>
#import <Metal/MTLVertexAttribute.h>
#import <Metal/MTLVertexAttributeDescriptor.h>
#import <Metal/MTLVertexAttributeDescriptorArray.h>
#import <Metal/MTLVertexBufferLayoutDescriptor.h>
#import <Metal/MTLVertexBufferLayoutDescriptorArray.h>
#import <Metal/MTLVertexDescriptor.h>
#import <Metal/_MTLCommandBuffer.h>
#import <Metal/_MTLCommandEncoder.h>
#import <Metal/_MTLCommandQueue.h>
#import <Metal/_MTLComputePipelineState.h>
#import <Metal/_MTLDebugCommandEncoder.h>
#import <Metal/_MTLDepthStencilState.h>
#import <Metal/_MTLDevice.h>
#import <Metal/_MTLFunction.h>
#import <Metal/_MTLLibrary.h>
#import <Metal/_MTLParallelRenderCommandEncoder.h>
#import <Metal/_MTLRenderPipelineState.h>
#import <Metal/_MTLSamplerState.h>
