// ManagedConfiguration.framework umbrella header
// Auto-generated from iOS 8.4.3 dyld_shared_cache (AppleTV 3,2)

#import <Foundation/Foundation.h>

#import <ManagedConfiguration/MCAPNConfiguration.h>
#import <ManagedConfiguration/MCAPNInfo.h>
#import <ManagedConfiguration/MCAPNPayload.h>
#import <ManagedConfiguration/MCARCHacks.h>
#import <ManagedConfiguration/MCAccountUtilities.h>
#import <ManagedConfiguration/MCAirPlayDestination.h>
#import <ManagedConfiguration/MCAirPlayPayload.h>
#import <ManagedConfiguration/MCAirPrintPayload.h>
#import <ManagedConfiguration/MCAppLayerVPNPayload.h>
#import <ManagedConfiguration/MCAppWhitelistPayloadBase.h>
#import <ManagedConfiguration/MCBook.h>
#import <ManagedConfiguration/MCBookmark.h>
#import <ManagedConfiguration/MCBookmarkManager.h>
#import <ManagedConfiguration/MCCalDAVAccountPayload.h>
#import <ManagedConfiguration/MCCardDAVAccountPayload.h>
#import <ManagedConfiguration/MCCellularPayload.h>
#import <ManagedConfiguration/MCCertificatePayload.h>
#import <ManagedConfiguration/MCCertificateWrapperProfile.h>
#import <ManagedConfiguration/MCChaperonePayload.h>
#import <ManagedConfiguration/MCCloudConfiguration.h>
#import <ManagedConfiguration/MCConfigurationProfile.h>
#import <ManagedConfiguration/MCCrypto.h>
#import <ManagedConfiguration/MCDefaultsPayload.h>
#import <ManagedConfiguration/MCDependencyReader.h>
#import <ManagedConfiguration/MCDeviceCapabilities.h>
#import <ManagedConfiguration/MCDomainsPayload.h>
#import <ManagedConfiguration/MCEASAccountPayload.h>
#import <ManagedConfiguration/MCEmailAccountPayload.h>
#import <ManagedConfiguration/MCEmailAccountPayloadBase.h>
#import <ManagedConfiguration/MCEncryptedProfileServicePayload.h>
#import <ManagedConfiguration/MCFontPayload.h>
#import <ManagedConfiguration/MCFormatterVendor.h>
#import <ManagedConfiguration/MCGlobalHTTPProxyPayload.h>
#import <ManagedConfiguration/MCHTTPRequestor.h>
#import <ManagedConfiguration/MCHTTPTransaction.h>
#import <ManagedConfiguration/MCHacks.h>
#import <ManagedConfiguration/MCInstallerReader.h>
#import <ManagedConfiguration/MCJobQueue.h>
#import <ManagedConfiguration/MCKeyValue.h>
#import <ManagedConfiguration/MCKeyValueSection.h>
#import <ManagedConfiguration/MCKeychain.h>
#import <ManagedConfiguration/MCLDAPAccountPayload.h>
#import <ManagedConfiguration/MCLanguageUtilities.h>
#import <ManagedConfiguration/MCLazyInitializationUtilities.h>
#import <ManagedConfiguration/MCMDMClient.h>
#import <ManagedConfiguration/MCMDMOptionsUtilities.h>
#import <ManagedConfiguration/MCMDMPayload.h>
#import <ManagedConfiguration/MCManagedAppManagerReader.h>
#import <ManagedConfiguration/MCManagedDefaultsManager.h>
#import <ManagedConfiguration/MCManagedDomainsCache.h>
#import <ManagedConfiguration/MCManagedDomainsCacheEntry.h>
#import <ManagedConfiguration/MCManagedMediaManagerReader.h>
#import <ManagedConfiguration/MCManifest.h>
#import <ManagedConfiguration/MCNetrbManager.h>
#import <ManagedConfiguration/MCNumber.h>
#import <ManagedConfiguration/MCPasscodeManager.h>
#import <ManagedConfiguration/MCPasswordPolicyPayload.h>
#import <ManagedConfiguration/MCPayload.h>
#import <ManagedConfiguration/MCPlainCertificatePayload.h>
#import <ManagedConfiguration/MCPowerAssertion.h>
#import <ManagedConfiguration/MCProcessAssertion.h>
#import <ManagedConfiguration/MCProfile.h>
#import <ManagedConfiguration/MCProfileConnection.h>
#import <ManagedConfiguration/MCProfileInfo.h>
#import <ManagedConfiguration/MCProfileServiceProfile.h>
#import <ManagedConfiguration/MCProfileTrustEvaluator.h>
#import <ManagedConfiguration/MCProfileWarning.h>
#import <ManagedConfiguration/MCRemovalPasswordPayload.h>
#import <ManagedConfiguration/MCRestrictionManager.h>
#import <ManagedConfiguration/MCRestrictionsPayload.h>
#import <ManagedConfiguration/MCSCEPPayload.h>
#import <ManagedConfiguration/MCSingleAppPayload.h>
#import <ManagedConfiguration/MCSingleSignOnPayload.h>
#import <ManagedConfiguration/MCSingleSignOnPayloadKerberosInfo.h>
#import <ManagedConfiguration/MCSubCalAccountPayload.h>
#import <ManagedConfiguration/MCTeslaConfiguration.h>
#import <ManagedConfiguration/MCTimerContext.h>
#import <ManagedConfiguration/MCTunnelParser.h>
#import <ManagedConfiguration/MCUnknownPayload.h>
#import <ManagedConfiguration/MCUserNotificationManager.h>
#import <ManagedConfiguration/MCUserNotificationQueueEntry.h>
#import <ManagedConfiguration/MCVPNPayload.h>
#import <ManagedConfiguration/MCVPNPayloadBase.h>
#import <ManagedConfiguration/MCVersioningUtilities.h>
#import <ManagedConfiguration/MCWAPIIdentityCertificatePayload.h>
#import <ManagedConfiguration/MCWebClipPayload.h>
#import <ManagedConfiguration/MCWebContentFilterPayload.h>
#import <ManagedConfiguration/MCWiFiPayload.h>
#import <ManagedConfiguration/MCWorkerThread.h>
