// PhotoLibraryServices.framework umbrella header
// Auto-generated from iOS 8.4.3 dyld_shared_cache (AppleTV 3,2)

#import <Foundation/Foundation.h>

#import <PhotoLibraryServices/AssetCollectionInfo.h>
#import <PhotoLibraryServices/PFAdjustment.h>
#import <PhotoLibraryServices/PFAdjustmentSerialization.h>
#import <PhotoLibraryServices/PFAdjustmentStack.h>
#import <PhotoLibraryServices/PFZlibDataCompression.h>
#import <PhotoLibraryServices/PFZlibDataCompressionOptions.h>
#import <PhotoLibraryServices/PFZlibDataDecompressionOptions.h>
#import <PhotoLibraryServices/PLAccountStore.h>
#import <PhotoLibraryServices/PLAdditionalAssetAttributes.h>
#import <PhotoLibraryServices/PLAggregateAlbumList.h>
#import <PhotoLibraryServices/PLAggregateAlbumListChangeNotification.h>
#import <PhotoLibraryServices/PLAssetChangeNotification.h>
#import <PhotoLibraryServices/PLAssetContainerChangeNotification.h>
#import <PhotoLibraryServices/PLAssetContainerListChangeNotification.h>
#import <PhotoLibraryServices/PLAssetDescription.h>
#import <PhotoLibraryServices/PLAssetFormats.h>
#import <PhotoLibraryServices/PLAssetSharingUtilities.h>
#import <PhotoLibraryServices/PLAssetToAlbumOrder.h>
#import <PhotoLibraryServices/PLAssetTransactionReason.h>
#import <PhotoLibraryServices/PLAssetsSaver.h>
#import <PhotoLibraryServices/PLAvalanche.h>
#import <PhotoLibraryServices/PLBBBulletin.h>
#import <PhotoLibraryServices/PLBBBulletinsManager.h>
#import <PhotoLibraryServices/PLBBPendingBulletinsBatch.h>
#import <PhotoLibraryServices/PLBulletinsTestDaemonJob.h>
#import <PhotoLibraryServices/PLCLoudSettingsChangedTrigger.h>
#import <PhotoLibraryServices/PLCPLStatus.h>
#import <PhotoLibraryServices/PLCacheDeleteTrigger.h>
#import <PhotoLibraryServices/PLCachedImage.h>
#import <PhotoLibraryServices/PLCameraPreviewImageWellChangeNotification.h>
#import <PhotoLibraryServices/PLChangeNode.h>
#import <PhotoLibraryServices/PLChangeNotification.h>
#import <PhotoLibraryServices/PLChangeNotificationCenter.h>
#import <PhotoLibraryServices/PLClientServerTransaction.h>
#import <PhotoLibraryServices/PLCloudAppInForegroundTrigger.h>
#import <PhotoLibraryServices/PLCloudBackgroundTransferMonitor.h>
#import <PhotoLibraryServices/PLCloudCommentsChangeNotification.h>
#import <PhotoLibraryServices/PLCloudDownloadAgent.h>
#import <PhotoLibraryServices/PLCloudDownloadOperation.h>
#import <PhotoLibraryServices/PLCloudExecutingScenario.h>
#import <PhotoLibraryServices/PLCloudFeedAssetsEntry.h>
#import <PhotoLibraryServices/PLCloudFeedCommentsEntry.h>
#import <PhotoLibraryServices/PLCloudFeedEntriesChangeNotification.h>
#import <PhotoLibraryServices/PLCloudFeedEntriesManager.h>
#import <PhotoLibraryServices/PLCloudFeedEntry.h>
#import <PhotoLibraryServices/PLCloudInflightTask.h>
#import <PhotoLibraryServices/PLCloudLibraryLayoutBucket.h>
#import <PhotoLibraryServices/PLCloudLibraryLayoutConfiguration.h>
#import <PhotoLibraryServices/PLCloudLibraryLayoutDistribution.h>
#import <PhotoLibraryServices/PLCloudLibraryLayoutStore.h>
#import <PhotoLibraryServices/PLCloudMaster.h>
#import <PhotoLibraryServices/PLCloudMasterMediaMetadata.h>
#import <PhotoLibraryServices/PLCloudMetadataChangedTrigger.h>
#import <PhotoLibraryServices/PLCloudMetadataStableTrigger.h>
#import <PhotoLibraryServices/PLCloudOperation.h>
#import <PhotoLibraryServices/PLCloudOperationResource.h>
#import <PhotoLibraryServices/PLCloudPendingResourceTask.h>
#import <PhotoLibraryServices/PLCloudPhotoLibraryBatchContainer.h>
#import <PhotoLibraryServices/PLCloudPhotoLibraryBatchManager.h>
#import <PhotoLibraryServices/PLCloudPhotoLibraryError.h>
#import <PhotoLibraryServices/PLCloudPhotoLibraryManager.h>
#import <PhotoLibraryServices/PLCloudPruneAgent.h>
#import <PhotoLibraryServices/PLCloudPruneOperation.h>
#import <PhotoLibraryServices/PLCloudResource.h>
#import <PhotoLibraryServices/PLCloudResourceNode.h>
#import <PhotoLibraryServices/PLCloudResourceRange.h>
#import <PhotoLibraryServices/PLCloudScenario.h>
#import <PhotoLibraryServices/PLCloudScenarioExecutionResult.h>
#import <PhotoLibraryServices/PLCloudScenarioProducer.h>
#import <PhotoLibraryServices/PLCloudScheduler.h>
#import <PhotoLibraryServices/PLCloudSchedulerConfiguration.h>
#import <PhotoLibraryServices/PLCloudSharedAlbum.h>
#import <PhotoLibraryServices/PLCloudSharedAlbumInvitationRecord.h>
#import <PhotoLibraryServices/PLCloudSharedAssetSaveJob.h>
#import <PhotoLibraryServices/PLCloudSharedComment.h>
#import <PhotoLibraryServices/PLCloudSharedCommentsJob.h>
#import <PhotoLibraryServices/PLCloudSharedDeleteAlbumsJob.h>
#import <PhotoLibraryServices/PLCloudSharedUpdateAlbumMetadataJob.h>
#import <PhotoLibraryServices/PLCloudSharingEnablingJob.h>
#import <PhotoLibraryServices/PLCloudSharingInvitationChangeJob.h>
#import <PhotoLibraryServices/PLCloudSharingJob.h>
#import <PhotoLibraryServices/PLCloudSharingResetJob.h>
#import <PhotoLibraryServices/PLCloudSharingViewedStateChangeJob.h>
#import <PhotoLibraryServices/PLCloudStatelessTrigger.h>
#import <PhotoLibraryServices/PLCloudStorageInfo.h>
#import <PhotoLibraryServices/PLCloudStreamShareJob.h>
#import <PhotoLibraryServices/PLCloudSystemStartedTrigger.h>
#import <PhotoLibraryServices/PLCloudTaskManager.h>
#import <PhotoLibraryServices/PLCloudTrigger.h>
#import <PhotoLibraryServices/PLContainerChangeNotification.h>
#import <PhotoLibraryServices/PLDaemonJob.h>
#import <PhotoLibraryServices/PLDateRangeFormatter.h>
#import <PhotoLibraryServices/PLDelayedFiledSystemDeletions.h>
#import <PhotoLibraryServices/PLDeletePhotosActionController.h>
#import <PhotoLibraryServices/PLDisconnectedManagedObjectContext.h>
#import <PhotoLibraryServices/PLDiskSpaceManagement.h>
#import <PhotoLibraryServices/PLDupeManager.h>
#import <PhotoLibraryServices/PLEmailAddressManager.h>
#import <PhotoLibraryServices/PLFaceDetectingImageSource.h>
#import <PhotoLibraryServices/PLFetchingAlbum.h>
#import <PhotoLibraryServices/PLFileSystemAssetImporter.h>
#import <PhotoLibraryServices/PLFileSystemImportAsset.h>
#import <PhotoLibraryServices/PLFilesystemDeletionInfo.h>
#import <PhotoLibraryServices/PLFilteredAlbum.h>
#import <PhotoLibraryServices/PLFilteredAlbumChangeNotification.h>
#import <PhotoLibraryServices/PLFilteredAlbumList.h>
#import <PhotoLibraryServices/PLFilteredAlbumListChangeNotification.h>
#import <PhotoLibraryServices/PLFilteredShuffledAlbum.h>
#import <PhotoLibraryServices/PLForegroundMonitor.h>
#import <PhotoLibraryServices/PLGenericAlbum.h>
#import <PhotoLibraryServices/PLImageCache.h>
#import <PhotoLibraryServices/PLImageCacheList.h>
#import <PhotoLibraryServices/PLImageGeometry.h>
#import <PhotoLibraryServices/PLImageLoadRequest.h>
#import <PhotoLibraryServices/PLImageLoadingQueue.h>
#import <PhotoLibraryServices/PLImageLoadingThread.h>
#import <PhotoLibraryServices/PLImageSource.h>
#import <PhotoLibraryServices/PLImageTable.h>
#import <PhotoLibraryServices/PLImageTableSegment.h>
#import <PhotoLibraryServices/PLImageWriter.h>
#import <PhotoLibraryServices/PLImportFileManager.h>
#import <PhotoLibraryServices/PLInFlightAssetsAlbum.h>
#import <PhotoLibraryServices/PLInFlightAssetsAlbumChangeNotification.h>
#import <PhotoLibraryServices/PLIndexMapper.h>
#import <PhotoLibraryServices/PLInvitationRecordsChangeNotification.h>
#import <PhotoLibraryServices/PLJPEGDataImage.h>
#import <PhotoLibraryServices/PLJPEGPreheatItem.h>
#import <PhotoLibraryServices/PLKeywordManager.h>
#import <PhotoLibraryServices/PLLargeImageLoader.h>
#import <PhotoLibraryServices/PLLoadRequestKey.h>
#import <PhotoLibraryServices/PLLocationController.h>
#import <PhotoLibraryServices/PLLocationUtils.h>
#import <PhotoLibraryServices/PLManagedAdjustment.h>
#import <PhotoLibraryServices/PLManagedAlbum.h>
#import <PhotoLibraryServices/PLManagedAlbumList.h>
#import <PhotoLibraryServices/PLManagedAsset.h>
#import <PhotoLibraryServices/PLManagedFace.h>
#import <PhotoLibraryServices/PLManagedFaceAlbum.h>
#import <PhotoLibraryServices/PLManagedFolder.h>
#import <PhotoLibraryServices/PLManagedKeyword.h>
#import <PhotoLibraryServices/PLManagedObject.h>
#import <PhotoLibraryServices/PLManagedObjectContext.h>
#import <PhotoLibraryServices/PLMappedImageData.h>
#import <PhotoLibraryServices/PLMergePolicy.h>
#import <PhotoLibraryServices/PLModelMigrator.h>
#import <PhotoLibraryServices/PLMoment.h>
#import <PhotoLibraryServices/PLMomentAnalyzer.h>
#import <PhotoLibraryServices/PLMomentAnalyzerGeoRequestInfo.h>
#import <PhotoLibraryServices/PLMomentAnalyzerQueue.h>
#import <PhotoLibraryServices/PLMomentAnalyzerWorkThread.h>
#import <PhotoLibraryServices/PLMomentCluster.h>
#import <PhotoLibraryServices/PLMomentClustering.h>
#import <PhotoLibraryServices/PLMomentGeneration.h>
#import <PhotoLibraryServices/PLMomentGenerationDataManager.h>
#import <PhotoLibraryServices/PLMomentLibrary.h>
#import <PhotoLibraryServices/PLMomentList.h>
#import <PhotoLibraryServices/PLMomentListCluster.h>
#import <PhotoLibraryServices/PLMomentListClustering.h>
#import <PhotoLibraryServices/PLMomentNameInfo.h>
#import <PhotoLibraryServices/PLMomentNode.h>
#import <PhotoLibraryServices/PLMomentNodeCache.h>
#import <PhotoLibraryServices/PLMomentTemporalSnapshot.h>
#import <PhotoLibraryServices/PLObjectSnapshot.h>
#import <PhotoLibraryServices/PLPTPdAssetEnumerator.h>
#import <PhotoLibraryServices/PLPTPdAssetManager.h>
#import <PhotoLibraryServices/PLPersistedAlbumMetadata.h>
#import <PhotoLibraryServices/PLPerson.h>
#import <PhotoLibraryServices/PLPersonInfoManager.h>
#import <PhotoLibraryServices/PLPersonReference.h>
#import <PhotoLibraryServices/PLPhotoBakedThumbnails.h>
#import <PhotoLibraryServices/PLPhotoBakedThumbnailsCollection.h>
#import <PhotoLibraryServices/PLPhotoDCFDirectory.h>
#import <PhotoLibraryServices/PLPhotoDCFFileGroup.h>
#import <PhotoLibraryServices/PLPhotoDCFObject.h>
#import <PhotoLibraryServices/PLPhotoDCIMDirectory.h>
#import <PhotoLibraryServices/PLPhotoDerivativeUtilities.h>
#import <PhotoLibraryServices/PLPhotoEditAdjustmentsVersion.h>
#import <PhotoLibraryServices/PLPhotoEditAggregateSession.h>
#import <PhotoLibraryServices/PLPhotoEditModel.h>
#import <PhotoLibraryServices/PLPhotoEditMutableModel.h>
#import <PhotoLibraryServices/PLPhotoEditPFDataConverter.h>
#import <PhotoLibraryServices/PLPhotoEditPersistenceManager.h>
#import <PhotoLibraryServices/PLPhotoEditRenderer.h>
#import <PhotoLibraryServices/PLPhotoEditTempDataConverter.h>
#import <PhotoLibraryServices/PLPhotoEffect.h>
#import <PhotoLibraryServices/PLPhotoLibrary.h>
#import <PhotoLibraryServices/PLPhotoLibraryImageSource.h>
#import <PhotoLibraryServices/PLPhotoLibraryShouldReloadNotification.h>
#import <PhotoLibraryServices/PLPhotoSharingHelper.h>
#import <PhotoLibraryServices/PLPhotoStreamAlbum.h>
#import <PhotoLibraryServices/PLPhotoStreamsHelper.h>
#import <PhotoLibraryServices/PLPhotosStateLog.h>
#import <PhotoLibraryServices/PLPlaceholderThumbnailManager.h>
#import <PhotoLibraryServices/PLPreheatItem.h>
#import <PhotoLibraryServices/PLProgressStack.h>
#import <PhotoLibraryServices/PLPropertyListFilter.h>
#import <PhotoLibraryServices/PLPropertyListFromDataTransformer.h>
#import <PhotoLibraryServices/PLPublishCloudSharedAssetsJob.h>
#import <PhotoLibraryServices/PLQuotaRequest.h>
#import <PhotoLibraryServices/PLRectValueFromDataTransformer.h>
#import <PhotoLibraryServices/PLRelationshipOrderKeyManager.h>
#import <PhotoLibraryServices/PLRelationshipOrderingState.h>
#import <PhotoLibraryServices/PLReplaceAssetsWithCameraRollCopiesJob.h>
#import <PhotoLibraryServices/PLRevGeoCompoundNameInfo.h>
#import <PhotoLibraryServices/PLRevGeoLocationInfo.h>
#import <PhotoLibraryServices/PLRevGeoPlace.h>
#import <PhotoLibraryServices/PLRevGeoPlaceInfo.h>
#import <PhotoLibraryServices/PLRevGeoRepresentativeNameInfo.h>
#import <PhotoLibraryServices/PLRotatedImage.h>
#import <PhotoLibraryServices/PLSMetadataUtilities.h>
#import <PhotoLibraryServices/PLSearchData.h>
#import <PhotoLibraryServices/PLSearchIndexDateFormatter.h>
#import <PhotoLibraryServices/PLSearchIndexManager.h>
#import <PhotoLibraryServices/PLSharedManagedObjectContext.h>
#import <PhotoLibraryServices/PLSharedPhotoLibrary.h>
#import <PhotoLibraryServices/PLShuffledAlbum.h>
#import <PhotoLibraryServices/PLShuffledAlbumChangeNotification.h>
#import <PhotoLibraryServices/PLSidecarFile.h>
#import <PhotoLibraryServices/PLSimpleAlbum.h>
#import <PhotoLibraryServices/PLSimpleAlbumList.h>
#import <PhotoLibraryServices/PLSimpleDCIMDirectory.h>
#import <PhotoLibraryServices/PLSlalomRangeMapper.h>
#import <PhotoLibraryServices/PLSlalomRangeMapperScaledRegion.h>
#import <PhotoLibraryServices/PLSlalomUtilities.h>
#import <PhotoLibraryServices/PLSortedAlbumList.h>
#import <PhotoLibraryServices/PLSortedAlbumListChangeNotification.h>
#import <PhotoLibraryServices/PLStreamShareSource.h>
#import <PhotoLibraryServices/PLSyncSaveJob.h>
#import <PhotoLibraryServices/PLTemporaryImageTable.h>
#import <PhotoLibraryServices/PLThrottleTimer.h>
#import <PhotoLibraryServices/PLThumbFileManager.h>
#import <PhotoLibraryServices/PLThumbnailIndexes.h>
#import <PhotoLibraryServices/PLThumbnailManager.h>
#import <PhotoLibraryServices/PLTransientManagedObjectContext.h>
#import <PhotoLibraryServices/PLTransientOrderKey.h>
#import <PhotoLibraryServices/PLUUIDStringFromUUIDDataTransformer.h>
#import <PhotoLibraryServices/PLUnmanagedAdjustment.h>
#import <PhotoLibraryServices/PLUserActivityDaemonJob.h>
#import <PhotoLibraryServices/PLUserActivityTrackerJob.h>
#import <PhotoLibraryServices/PLVideoTranscoder.h>
#import <PhotoLibraryServices/PLWallpaperAlbum.h>
#import <PhotoLibraryServices/PLWallpaperAsset.h>
#import <PhotoLibraryServices/PLWallpaperImporter.h>
#import <PhotoLibraryServices/PLWarningHelper.h>
#import <PhotoLibraryServices/PLWeakRef.h>
#import <PhotoLibraryServices/PSIAsset.h>
#import <PhotoLibraryServices/PSIDatabase.h>
#import <PhotoLibraryServices/PSIGroup.h>
#import <PhotoLibraryServices/PSIGroupAggregate.h>
#import <PhotoLibraryServices/PSIGroupResult.h>
#import <PhotoLibraryServices/PSIQuery.h>
#import <PhotoLibraryServices/PSIReusableObject.h>
#import <PhotoLibraryServices/PSITokenizer.h>
#import <PhotoLibraryServices/_PLClientTransaction.h>
#import <PhotoLibraryServices/_PLDataPreheatItem.h>
#import <PhotoLibraryServices/_PLFetchingAlbum.h>
#import <PhotoLibraryServices/_PLGenericAlbum.h>
#import <PhotoLibraryServices/_PLJPEGThumbnailPreheatItem.h>
#import <PhotoLibraryServices/_PLKnownAdjustment.h>
#import <PhotoLibraryServices/_PLLargeJPEGPreheatItem.h>
#import <PhotoLibraryServices/_PLLazyPreheatData.h>
#import <PhotoLibraryServices/_PLManagedAdjustment.h>
#import <PhotoLibraryServices/_PLManagedAlbum.h>
#import <PhotoLibraryServices/_PLManagedAlbumList.h>
#import <PhotoLibraryServices/_PLManagedKeyword.h>
#import <PhotoLibraryServices/_PLPhotoLibraryFileReservation.h>
#import <PhotoLibraryServices/_PLPlaceholderThumbnailCachedData.h>
#import <PhotoLibraryServices/_PLServerTransaction.h>
#import <PhotoLibraryServices/_PLSidecarFile.h>
