// iCalendar.framework umbrella header
// Auto-generated from iOS 8.4.3 dyld_shared_cache (AppleTV 3,2)

#import <Foundation/Foundation.h>

#import <iCalendar/ICSActionValue.h>
#import <iCalendar/ICSAlarm.h>
#import <iCalendar/ICSAttachment.h>
#import <iCalendar/ICSAttendeeComment.h>
#import <iCalendar/ICSAvailability.h>
#import <iCalendar/ICSAvailable.h>
#import <iCalendar/ICSBusyStatusValue.h>
#import <iCalendar/ICSByDayValue.h>
#import <iCalendar/ICSCalendar.h>
#import <iCalendar/ICSCalendarServerAccessValue.h>
#import <iCalendar/ICSCalendarUserParameter.h>
#import <iCalendar/ICSClassificationValue.h>
#import <iCalendar/ICSColor.h>
#import <iCalendar/ICSComponent.h>
#import <iCalendar/ICSConference.h>
#import <iCalendar/ICSDate.h>
#import <iCalendar/ICSDateTimeUTCValue.h>
#import <iCalendar/ICSDateTimeValue.h>
#import <iCalendar/ICSDateValue.h>
#import <iCalendar/ICSDocument.h>
#import <iCalendar/ICSDuration.h>
#import <iCalendar/ICSEvent.h>
#import <iCalendar/ICSFreeBusy.h>
#import <iCalendar/ICSFreeBusyTime.h>
#import <iCalendar/ICSFreeBusyTypeParameter.h>
#import <iCalendar/ICSJournal.h>
#import <iCalendar/ICSLogger.h>
#import <iCalendar/ICSMethodValue.h>
#import <iCalendar/ICSMultiValueProperty.h>
#import <iCalendar/ICSParser.h>
#import <iCalendar/ICSParticipationStatusParameter.h>
#import <iCalendar/ICSPeriod.h>
#import <iCalendar/ICSPredefinedValue.h>
#import <iCalendar/ICSProperty.h>
#import <iCalendar/ICSRecurrenceRule.h>
#import <iCalendar/ICSRoleParameter.h>
#import <iCalendar/ICSScheduleAgentParameter.h>
#import <iCalendar/ICSScheduleForceSendParameter.h>
#import <iCalendar/ICSScheduleStatusParameter.h>
#import <iCalendar/ICSStatusValue.h>
#import <iCalendar/ICSStructuredLocation.h>
#import <iCalendar/ICSTimeZone.h>
#import <iCalendar/ICSTimeZoneBlock.h>
#import <iCalendar/ICSTimeZoneChange.h>
#import <iCalendar/ICSTimeZoneDaylightBlock.h>
#import <iCalendar/ICSTimeZoneStandardBlock.h>
#import <iCalendar/ICSTimeZoneTranslator.h>
#import <iCalendar/ICSTodo.h>
#import <iCalendar/ICSTokenizer.h>
#import <iCalendar/ICSTransparencyValue.h>
#import <iCalendar/ICSTravelAdvisoryBehavior.h>
#import <iCalendar/ICSTravelDuration.h>
#import <iCalendar/ICSTrigger.h>
#import <iCalendar/ICSUserAddress.h>
