// AppleTVServices.framework umbrella header
// Auto-generated from iOS 8.4.3 dyld_shared_cache (AppleTV 3,2)

#import <Foundation/Foundation.h>

#import <AppleTVServices/ATV2SVerificationOperation.h>
#import <AppleTVServices/ATVAVMetadataItemImageLoader.h>
#import <AppleTVServices/ATVAVTimedMetadataGroupChapter.h>
#import <AppleTVServices/ATVAcquisitionProperties.h>
#import <AppleTVServices/ATVAcquisitionRequest.h>
#import <AppleTVServices/ATVAssetGroup.h>
#import <AppleTVServices/ATVAssetLibrary.h>
#import <AppleTVServices/ATVAudioOption.h>
#import <AppleTVServices/ATVAudioSubtitleUtilities.h>
#import <AppleTVServices/ATVAudioVideoSettings.h>
#import <AppleTVServices/ATVAuthenticationContext.h>
#import <AppleTVServices/ATVAutoSubtitleOption.h>
#import <AppleTVServices/ATVAutounbinder.h>
#import <AppleTVServices/ATVBackgroundQueuePlayer.h>
#import <AppleTVServices/ATVBackgroundTask.h>
#import <AppleTVServices/ATVBackgroundTaskManager.h>
#import <AppleTVServices/ATVBaseMediaItem.h>
#import <AppleTVServices/ATVBindingAdaptor.h>
#import <AppleTVServices/ATVBindingInfo.h>
#import <AppleTVServices/ATVBookmark.h>
#import <AppleTVServices/ATVBookmarkKey.h>
#import <AppleTVServices/ATVBookmarkService.h>
#import <AppleTVServices/ATVBoundaryTimeObserverInfo.h>
#import <AppleTVServices/ATVBumperConfig.h>
#import <AppleTVServices/ATVCFUserNotification.h>
#import <AppleTVServices/ATVCVVVerificationOperation.h>
#import <AppleTVServices/ATVChapter.h>
#import <AppleTVServices/ATVChapterCollection.h>
#import <AppleTVServices/ATVClientVersionEvaluation.h>
#import <AppleTVServices/ATVCloudAlbumQueryHandler.h>
#import <AppleTVServices/ATVCloudArtistQueryHandler.h>
#import <AppleTVServices/ATVCloudCollection.h>
#import <AppleTVServices/ATVCloudCollectionQueryHandler.h>
#import <AppleTVServices/ATVCloudComposerQueryHandler.h>
#import <AppleTVServices/ATVCloudDataClient.h>
#import <AppleTVServices/ATVCloudGenreQueryHandler.h>
#import <AppleTVServices/ATVCloudItem.h>
#import <AppleTVServices/ATVCloudItemQueryHandler.h>
#import <AppleTVServices/ATVCloudPlaylistQueryHandler.h>
#import <AppleTVServices/ATVCloudQueryHandler.h>
#import <AppleTVServices/ATVConflictResolverEntry.h>
#import <AppleTVServices/ATVDMAPBuffer.h>
#import <AppleTVServices/ATVDMAPResponse.h>
#import <AppleTVServices/ATVDataClient.h>
#import <AppleTVServices/ATVDataClientConnector.h>
#import <AppleTVServices/ATVDataClientResultsController.h>
#import <AppleTVServices/ATVDataCollection.h>
#import <AppleTVServices/ATVDataImageRequest.h>
#import <AppleTVServices/ATVDataItem.h>
#import <AppleTVServices/ATVDataMediaItem.h>
#import <AppleTVServices/ATVDataQuery.h>
#import <AppleTVServices/ATVDataQueryCompoundFilter.h>
#import <AppleTVServices/ATVDataQueryFilter.h>
#import <AppleTVServices/ATVDataQueryProcessor.h>
#import <AppleTVServices/ATVDataQueryRecord.h>
#import <AppleTVServices/ATVDataServer.h>
#import <AppleTVServices/ATVDataType.h>
#import <AppleTVServices/ATVDateRange.h>
#import <AppleTVServices/ATVDecoratorRequest.h>
#import <AppleTVServices/ATVDevice.h>
#import <AppleTVServices/ATVDiskSpaceUtility.h>
#import <AppleTVServices/ATVDisplayManager.h>
#import <AppleTVServices/ATVDisplayMode.h>
#import <AppleTVServices/ATVDocumentJSONDeserializationPostProcessor.h>
#import <AppleTVServices/ATVDocumentLoader.h>
#import <AppleTVServices/ATVDocumentPlistDeserializationPostProcessor.h>
#import <AppleTVServices/ATVDocumentStoreProtocolPostprocessor.h>
#import <AppleTVServices/ATVEthernetInterface.h>
#import <AppleTVServices/ATVEvaluation.h>
#import <AppleTVServices/ATVFairPlayContext.h>
#import <AppleTVServices/ATVHSAccountInfo.h>
#import <AppleTVServices/ATVHSConnection.h>
#import <AppleTVServices/ATVHSDAAPAssetData.h>
#import <AppleTVServices/ATVHSDAAPCollection.h>
#import <AppleTVServices/ATVHSDAAPItem.h>
#import <AppleTVServices/ATVHSDPAPAssetData.h>
#import <AppleTVServices/ATVHSDPAPCollection.h>
#import <AppleTVServices/ATVHSDPAPItem.h>
#import <AppleTVServices/ATVHSDataClient.h>
#import <AppleTVServices/ATVHSDataClientConfiguration.h>
#import <AppleTVServices/ATVHSDataClientConnectionConfiguration.h>
#import <AppleTVServices/ATVHSDataClientSessionConfiguration.h>
#import <AppleTVServices/ATVHSDataServer.h>
#import <AppleTVServices/ATVHSDataServerConfiguration.h>
#import <AppleTVServices/ATVHSDataServerID.h>
#import <AppleTVServices/ATVHSDataServerManager.h>
#import <AppleTVServices/ATVHSHelper.h>
#import <AppleTVServices/ATVHSHomeShareConfiguration.h>
#import <AppleTVServices/ATVHSKeybagRentalCheckinOperation.h>
#import <AppleTVServices/ATVHSKeybagRentalCheckoutOperation.h>
#import <AppleTVServices/ATVHSKeybagRentalRequest.h>
#import <AppleTVServices/ATVHSKeybagStore.h>
#import <AppleTVServices/ATVHSKeybagSynchronizer.h>
#import <AppleTVServices/ATVHSMediaItem.h>
#import <AppleTVServices/ATVHSQueryHelper.h>
#import <AppleTVServices/ATVHSRentalInfo.h>
#import <AppleTVServices/ATVHSRequest.h>
#import <AppleTVServices/ATVHSRequestContext.h>
#import <AppleTVServices/ATVHSResponseParser.h>
#import <AppleTVServices/ATVHSServiceClient.h>
#import <AppleTVServices/ATVHSServiceClientDataClient.h>
#import <AppleTVServices/ATVHSServiceClientFairPlaySAPEncrypter.h>
#import <AppleTVServices/ATVHSServiceClientInterface.h>
#import <AppleTVServices/ATVHSServiceInterface.h>
#import <AppleTVServices/ATVHSStandaloneDataClient.h>
#import <AppleTVServices/ATVHSStandaloneFairPlaySAPEncrypter.h>
#import <AppleTVServices/ATVHSStoreAccount.h>
#import <AppleTVServices/ATVITMSPushNotificationRegistrar.h>
#import <AppleTVServices/ATVITunesStoreDataItem.h>
#import <AppleTVServices/ATVImage.h>
#import <AppleTVServices/ATVImageProxy.h>
#import <AppleTVServices/ATVImageScaleDecorator.h>
#import <AppleTVServices/ATVInternationalization.h>
#import <AppleTVServices/ATVJSCallback.h>
#import <AppleTVServices/ATVJSClassWrapper.h>
#import <AppleTVServices/ATVJavaScriptContext.h>
#import <AppleTVServices/ATVJingleImageDecrypter.h>
#import <AppleTVServices/ATVJingleTrickplayDecrypter.h>
#import <AppleTVServices/ATVLeaseAgent.h>
#import <AppleTVServices/ATVLogger.h>
#import <AppleTVServices/ATVMachineDataOperation.h>
#import <AppleTVServices/ATVMediaCacheManager.h>
#import <AppleTVServices/ATVMediaItemLoader.h>
#import <AppleTVServices/ATVMediaItemTimingData.h>
#import <AppleTVServices/ATVMonitoredItemInfo.h>
#import <AppleTVServices/ATVMutableBookmark.h>
#import <AppleTVServices/ATVMutableChapter.h>
#import <AppleTVServices/ATVMutableChapterCollection.h>
#import <AppleTVServices/ATVNetworkInterface.h>
#import <AppleTVServices/ATVNetworkUtilities.h>
#import <AppleTVServices/ATVObjectKeyPathPair.h>
#import <AppleTVServices/ATVOffSubtitleOption.h>
#import <AppleTVServices/ATVPeripheralFirmwareScannerOperation.h>
#import <AppleTVServices/ATVPeripheralFirmwareUpdaterOperation.h>
#import <AppleTVServices/ATVPeripheralManager.h>
#import <AppleTVServices/ATVPlaybackImageLoadInfo.h>
#import <AppleTVServices/ATVPlaybackState.h>
#import <AppleTVServices/ATVPlaybackUtilities.h>
#import <AppleTVServices/ATVPlayer.h>
#import <AppleTVServices/ATVPlayerBookmarkMonitor.h>
#import <AppleTVServices/ATVPlayerDebugInfoView.h>
#import <AppleTVServices/ATVPlayerItem.h>
#import <AppleTVServices/ATVPlayerLayerView.h>
#import <AppleTVServices/ATVPlaylist.h>
#import <AppleTVServices/ATVPodcastBookmarkKey.h>
#import <AppleTVServices/ATVPodcastGUID.h>
#import <AppleTVServices/ATVPowerManager.h>
#import <AppleTVServices/ATVPreferenceManager.h>
#import <AppleTVServices/ATVPreferences.h>
#import <AppleTVServices/ATVProcessManager.h>
#import <AppleTVServices/ATVProxyArray.h>
#import <AppleTVServices/ATVPushNotificationServer.h>
#import <AppleTVServices/ATVPushNotificationTypeOperation.h>
#import <AppleTVServices/ATVRentalItemExpirationTask.h>
#import <AppleTVServices/ATVRunloopInstrumentation.h>
#import <AppleTVServices/ATVSecureKeyDeliveryCoordinator.h>
#import <AppleTVServices/ATVSecureKeyISLoader.h>
#import <AppleTVServices/ATVSecureKeyJavascriptLoader.h>
#import <AppleTVServices/ATVSecureKeyLoader.h>
#import <AppleTVServices/ATVSecureKeyRequest.h>
#import <AppleTVServices/ATVSecureKeyStandardConnector.h>
#import <AppleTVServices/ATVSecureKeyStandardLoader.h>
#import <AppleTVServices/ATVStateMachine.h>
#import <AppleTVServices/ATVStoreAccountManager.h>
#import <AppleTVServices/ATVStoreBumperConfig.h>
#import <AppleTVServices/ATVStoreEnvironment.h>
#import <AppleTVServices/ATVStoreFront.h>
#import <AppleTVServices/ATVStoreFrontLocale.h>
#import <AppleTVServices/ATVStoreMediaToken.h>
#import <AppleTVServices/ATVStoreMediaTokenDecoder.h>
#import <AppleTVServices/ATVStoreMediaTokenService.h>
#import <AppleTVServices/ATVStorePermissionMonitor.h>
#import <AppleTVServices/ATVStoreURLBag.h>
#import <AppleTVServices/ATVSubtitleOption.h>
#import <AppleTVServices/ATVSyncingKeyValueStore.h>
#import <AppleTVServices/ATVTimeProfiler.h>
#import <AppleTVServices/ATVTimeRange.h>
#import <AppleTVServices/ATVUPPClientState.h>
#import <AppleTVServices/ATVUPPUpdateRecord.h>
#import <AppleTVServices/ATVURLImageLoadRequest.h>
#import <AppleTVServices/ATVURLImageLoader.h>
#import <AppleTVServices/ATVURLImageRequest.h>
#import <AppleTVServices/ATVURLMediaItem.h>
#import <AppleTVServices/ATVURLOperationNoCookies.h>
#import <AppleTVServices/ATVUniversalPlaybackPositionClient.h>
#import <AppleTVServices/ATVUniversalPlaybackPositionRecord.h>
#import <AppleTVServices/ATVUniversalPlaybackPositionTransactionContext.h>
#import <AppleTVServices/ATVUserNotificationCenter.h>
#import <AppleTVServices/ATVVideoView.h>
#import <AppleTVServices/ATVWiFiInterface.h>
#import <AppleTVServices/ATVXMLDocument.h>
#import <AppleTVServices/ATVXMLDocumentFragment.h>
#import <AppleTVServices/ATVXMLElement.h>
#import <AppleTVServices/ATVXMLNode.h>
#import <AppleTVServices/ATVXMLSchema.h>
#import <AppleTVServices/ATViCloudAccountManager.h>
#import <AppleTVServices/ATViCloudTermsStringRequest.h>
#import <AppleTVServices/ATViTunesKeyValueStoreAPIUtils.h>
#import <AppleTVServices/ATViTunesKeyValueStoreSyncAPI.h>
#import <AppleTVServices/ATViTunesKeyValueStoreSyncItem.h>
#import <AppleTVServices/ATViTunesKeyValueStoreSyncResponse.h>
#import <AppleTVServices/XMLNodeData.h>
