// EventKit.framework umbrella header
// Auto-generated from iOS 8.4.3 dyld_shared_cache (AppleTV 3,2)

#import <Foundation/Foundation.h>

#import <EventKit/CADEntityWrapper.h>
#import <EventKit/CADEventEntityWrapper.h>
#import <EventKit/CADXPCProxyHelper.h>
#import <EventKit/CalAlarmMetadata.h>
#import <EventKit/CalItemMetadata.h>
#import <EventKit/CalSearch.h>
#import <EventKit/CalSpotlightSearch.h>
#import <EventKit/EKAlarm.h>
#import <EventKit/EKAlarmOccurrence.h>
#import <EventKit/EKAttachment.h>
#import <EventKit/EKAttendee.h>
#import <EventKit/EKAvailabilityCache.h>
#import <EventKit/EKAvailabilityCachedSpan.h>
#import <EventKit/EKAvailabilityCachedSpanRange.h>
#import <EventKit/EKAvailabilitySpan.h>
#import <EventKit/EKCalendar.h>
#import <EventKit/EKCalendarDate.h>
#import <EventKit/EKCalendarEventInvitationNotification.h>
#import <EventKit/EKCalendarEventInvitationNotificationAttendee.h>
#import <EventKit/EKCalendarFilter.h>
#import <EventKit/EKCalendarInviteReplyNotification.h>
#import <EventKit/EKCalendarItem.h>
#import <EventKit/EKCalendarItemAlertInfo.h>
#import <EventKit/EKCalendarItemsWithExternalIdentifierPredicate.h>
#import <EventKit/EKCalendarNotification.h>
#import <EventKit/EKCalendarNotificationReference.h>
#import <EventKit/EKCalendarResourceChangeNotification.h>
#import <EventKit/EKCalendarSharedCalendarNotification.h>
#import <EventKit/EKDaemonConnection.h>
#import <EventKit/EKDebugPreferences.h>
#import <EventKit/EKDirectoryGroup.h>
#import <EventKit/EKDirectoryLocation.h>
#import <EventKit/EKDirectoryPerson.h>
#import <EventKit/EKDirectoryRecord.h>
#import <EventKit/EKDirectoryResource.h>
#import <EventKit/EKDirectorySearchOperation.h>
#import <EventKit/EKDirectorySearchQuery.h>
#import <EventKit/EKDirectorySearchResultSet.h>
#import <EventKit/EKEvent.h>
#import <EventKit/EKEventCreatedFromSuggestionPredicate.h>
#import <EventKit/EKEventOccurrenceInfo.h>
#import <EventKit/EKEventPredicate.h>
#import <EventKit/EKEventStore.h>
#import <EventKit/EKInviteReplyNotification.h>
#import <EventKit/EKMasterEventsPredicate.h>
#import <EventKit/EKMutableCalendarDate.h>
#import <EventKit/EKNotifiableEventsPredicate.h>
#import <EventKit/EKNotificationCenterVisibleEventsPredicate.h>
#import <EventKit/EKObject.h>
#import <EventKit/EKObjectID.h>
#import <EventKit/EKObjectRelation.h>
#import <EventKit/EKObjectToManyRelation.h>
#import <EventKit/EKObjectToOneRelation.h>
#import <EventKit/EKOccurrenceCacheLocationSearch.h>
#import <EventKit/EKOccurrenceCacheSearch.h>
#import <EventKit/EKOrganizer.h>
#import <EventKit/EKParticipant.h>
#import <EventKit/EKPersistentAlarm.h>
#import <EventKit/EKPersistentAttachment.h>
#import <EventKit/EKPersistentAttendee.h>
#import <EventKit/EKPersistentCalendar.h>
#import <EventKit/EKPersistentCalendarItem.h>
#import <EventKit/EKPersistentChangeStoreInfo.h>
#import <EventKit/EKPersistentChangeStoreRowInfo.h>
#import <EventKit/EKPersistentEvent.h>
#import <EventKit/EKPersistentEventAction.h>
#import <EventKit/EKPersistentExceptionDate.h>
#import <EventKit/EKPersistentInviteReplyNotification.h>
#import <EventKit/EKPersistentLocation.h>
#import <EventKit/EKPersistentObject.h>
#import <EventKit/EKPersistentOrganizer.h>
#import <EventKit/EKPersistentParticipant.h>
#import <EventKit/EKPersistentRecurrenceRule.h>
#import <EventKit/EKPersistentReminder.h>
#import <EventKit/EKPersistentResourceChange.h>
#import <EventKit/EKPersistentSharee.h>
#import <EventKit/EKPersistentSource.h>
#import <EventKit/EKPredicate.h>
#import <EventKit/EKPredicateSearch.h>
#import <EventKit/EKPreferences.h>
#import <EventKit/EKRecurrenceDayOfWeek.h>
#import <EventKit/EKRecurrenceEnd.h>
#import <EventKit/EKRecurrenceGenerator.h>
#import <EventKit/EKRecurrenceHelper.h>
#import <EventKit/EKRecurrenceRule.h>
#import <EventKit/EKRelation.h>
#import <EventKit/EKReminder.h>
#import <EventKit/EKReminderPredicate.h>
#import <EventKit/EKRequestAvailabilityOperation.h>
#import <EventKit/EKResourceChange.h>
#import <EventKit/EKRespondedEventsPredicate.h>
#import <EventKit/EKScheduledReminderPredicate.h>
#import <EventKit/EKSharee.h>
#import <EventKit/EKSideAlarm.h>
#import <EventKit/EKSideTableContext.h>
#import <EventKit/EKSocialURLSearchDelegate.h>
#import <EventKit/EKSource.h>
#import <EventKit/EKSourceConstraints.h>
#import <EventKit/EKStats.h>
#import <EventKit/EKStructuredLocation.h>
#import <EventKit/EKTimeZone.h>
#import <EventKit/EKTravelAdvice.h>
#import <EventKit/EKTravelAdvisor.h>
#import <EventKit/EKTravelAdvisorRealWorld.h>
#import <EventKit/EKTravelAdvisorTraceLocation.h>
#import <EventKit/EKTravelAdvisorTracePrediction.h>
#import <EventKit/EKTravelAgendaItem.h>
#import <EventKit/EKTravelEngine.h>
#import <EventKit/EKTravelEngineAgendaEntry.h>
#import <EventKit/EKTravelEngineThrottle.h>
#import <EventKit/EKTravelEngineThrottledAdvice.h>
#import <EventKit/EKTravelEngineUtilities.h>
#import <EventKit/EKTravelEventsPredicate.h>
#import <EventKit/EKTravelLookupManager.h>
#import <EventKit/EKTravelPrediction.h>
#import <EventKit/EKTravelPredictionCar.h>
#import <EventKit/EKTravelPredictionWalking.h>
#import <EventKit/EKTravelRealRoutePredictor.h>
#import <EventKit/EKTravelRealRoutePredictorInternalDelegate.h>
#import <EventKit/EKUnacknowledgedEventsPredicate.h>
#import <EventKit/EKUnalertedEventsPredicate.h>
#import <EventKit/EKUpcomingEventsPredicate.h>
#import <EventKit/EKWatchdog.h>
#import <EventKit/StatsOperation.h>
#import <EventKit/_EKAlarmEngine.h>
#import <EventKit/_EKNotificationMonitor.h>
