// TelephonyUI.framework umbrella header
// Auto-generated from iOS 8.4.3 dyld_shared_cache (AppleTV 3,2)

#import <Foundation/Foundation.h>

#import <TelephonyUI/TPAlertViewHelper.h>
#import <TelephonyUI/TPBackgroundRoundedRectView.h>
#import <TelephonyUI/TPBottomBar.h>
#import <TelephonyUI/TPBottomDoubleButtonBar.h>
#import <TelephonyUI/TPBottomSingleButtonBar.h>
#import <TelephonyUI/TPButton.h>
#import <TelephonyUI/TPDialerNumberPad.h>
#import <TelephonyUI/TPDialerSoundController.h>
#import <TelephonyUI/TPFakeSixSquareButton.h>
#import <TelephonyUI/TPFakeSixSquareButtonView.h>
#import <TelephonyUI/TPLCDBar.h>
#import <TelephonyUI/TPLCDSubImageView.h>
#import <TelephonyUI/TPLCDTextView.h>
#import <TelephonyUI/TPLCDTextViewScrollingView.h>
#import <TelephonyUI/TPLCDView.h>
#import <TelephonyUI/TPLegacyBottomBar.h>
#import <TelephonyUI/TPLegacyBottomDoubleButtonBar.h>
#import <TelephonyUI/TPLegacyBottomLockBar.h>
#import <TelephonyUI/TPLegacyBottomSingleButtonBar.h>
#import <TelephonyUI/TPLegacyButton.h>
#import <TelephonyUI/TPLegacyCallWaitingButton.h>
#import <TelephonyUI/TPLegacyLCDBar.h>
#import <TelephonyUI/TPLegacyLCDSubImageView.h>
#import <TelephonyUI/TPLegacyLCDTextView.h>
#import <TelephonyUI/TPLegacyLCDTextViewScrollingView.h>
#import <TelephonyUI/TPLegacyLCDView.h>
#import <TelephonyUI/TPLegacyLockKnobView.h>
#import <TelephonyUI/TPLegacyLockTextView.h>
#import <TelephonyUI/TPLegacyPhonePad.h>
#import <TelephonyUI/TPLegacyWell.h>
#import <TelephonyUI/TPNumberPad.h>
#import <TelephonyUI/TPNumberPadButton.h>
#import <TelephonyUI/TPNumberPadDarkStyleButton.h>
#import <TelephonyUI/TPNumberPadLightStyleButton.h>
#import <TelephonyUI/TPPasscodeView.h>
#import <TelephonyUI/TPPathView.h>
#import <TelephonyUI/TPPhonePad.h>
#import <TelephonyUI/TPPortraitOnlyNavigationController.h>
#import <TelephonyUI/TPRevealingRingView.h>
#import <TelephonyUI/TPRingView.h>
#import <TelephonyUI/TPSetPINViewController.h>
#import <TelephonyUI/TPSimpleNumberPad.h>
#import <TelephonyUI/TPSimpleNumberPadButton.h>
#import <TelephonyUI/TPSlidingButton.h>
#import <TelephonyUI/TPStarkDividerView.h>
#import <TelephonyUI/TPStarkInCallButton.h>
#import <TelephonyUI/TPStarkInCallButtonRing.h>
#import <TelephonyUI/TPStarkInCallButtonsView.h>
#import <TelephonyUI/TPStarkInCallHardPauseButton.h>
#import <TelephonyUI/TPStarkInCallViewController.h>
#import <TelephonyUI/TPStarkPhoneCallContainer.h>
#import <TelephonyUI/TPStarkPhoneCallGalleryView.h>
#import <TelephonyUI/TPStarkPhoneCallViewCell.h>
#import <TelephonyUI/TPStarkUtilities.h>
#import <TelephonyUI/TPSuperBottomBar.h>
#import <TelephonyUI/TPSuperBottomBarButton.h>
#import <TelephonyUI/TPSuperBottomBarSupplementalButton.h>
#import <TelephonyUI/TPWallpaperView.h>
