// AssistantServices.framework umbrella header
// Auto-generated from iOS 8.4.3 dyld_shared_cache (AppleTV 3,2)

#import <Foundation/Foundation.h>

#import <AssistantServices/AFAccount.h>
#import <AssistantServices/AFAggregator.h>
#import <AssistantServices/AFAlarm.h>
#import <AssistantServices/AFAppContextAggregator.h>
#import <AssistantServices/AFApplicationInfo.h>
#import <AssistantServices/AFBulletin.h>
#import <AssistantServices/AFCall.h>
#import <AssistantServices/AFCity.h>
#import <AssistantServices/AFConnection.h>
#import <AssistantServices/AFConnectionClientServiceDelegate.h>
#import <AssistantServices/AFContactAddress.h>
#import <AssistantServices/AFContextManager.h>
#import <AssistantServices/AFContextRequest.h>
#import <AssistantServices/AFContextResponse.h>
#import <AssistantServices/AFCreateAlarmRequest.h>
#import <AssistantServices/AFCreateAlarmResponse.h>
#import <AssistantServices/AFCreateMessageRequest.h>
#import <AssistantServices/AFDeleteAlarmRequest.h>
#import <AssistantServices/AFDictationConnection.h>
#import <AssistantServices/AFDictationConnectionServiceDelegate.h>
#import <AssistantServices/AFDictationOptions.h>
#import <AssistantServices/AFDistributedMessagingCenterContextProvider.h>
#import <AssistantServices/AFError.h>
#import <AssistantServices/AFFuture.h>
#import <AssistantServices/AFGetSettingsRequest.h>
#import <AssistantServices/AFGetSettingsResponse.h>
#import <AssistantServices/AFGetTimerRequest.h>
#import <AssistantServices/AFGetTimerResponse.h>
#import <AssistantServices/AFInitiateCallRequest.h>
#import <AssistantServices/AFLocation.h>
#import <AssistantServices/AFMachServiceSiriTaskDeliverer.h>
#import <AssistantServices/AFManagedStorageConnection.h>
#import <AssistantServices/AFMessage.h>
#import <AssistantServices/AFMetrics.h>
#import <AssistantServices/AFObjectCreatedSiriResponse.h>
#import <AssistantServices/AFObjectUpdatedSiriResponse.h>
#import <AssistantServices/AFPerson.h>
#import <AssistantServices/AFPersonContactHandle.h>
#import <AssistantServices/AFPreferences.h>
#import <AssistantServices/AFSUPFunctionProvider.h>
#import <AssistantServices/AFSearchAlarmsRequest.h>
#import <AssistantServices/AFSearchAlarmsResponse.h>
#import <AssistantServices/AFSetSettingsRequest.h>
#import <AssistantServices/AFSetSettingsResponse.h>
#import <AssistantServices/AFSetTimerRequest.h>
#import <AssistantServices/AFSetting.h>
#import <AssistantServices/AFSettingChange.h>
#import <AssistantServices/AFSettingsConnection.h>
#import <AssistantServices/AFShowAlarmRequest.h>
#import <AssistantServices/AFShowNextEventRequest.h>
#import <AssistantServices/AFShowSettingRequest.h>
#import <AssistantServices/AFShowTimerRequest.h>
#import <AssistantServices/AFSiriContext.h>
#import <AssistantServices/AFSiriModelObject.h>
#import <AssistantServices/AFSiriRequest.h>
#import <AssistantServices/AFSiriRequestSucceededResponse.h>
#import <AssistantServices/AFSiriResponse.h>
#import <AssistantServices/AFSiriTask.h>
#import <AssistantServices/AFSiriTaskContextProvider.h>
#import <AssistantServices/AFSiriTaskDeliveryHandler.h>
#import <AssistantServices/AFSiriTaskExecution.h>
#import <AssistantServices/AFSiriTaskMetricsManager.h>
#import <AssistantServices/AFSiriTaskService.h>
#import <AssistantServices/AFSiriTaskUsageResult.h>
#import <AssistantServices/AFSiriTaskmaster.h>
#import <AssistantServices/AFSpeakableUtteranceParser.h>
#import <AssistantServices/AFSpeechCorrectionInfo.h>
#import <AssistantServices/AFSpeechInterpretation.h>
#import <AssistantServices/AFSpeechPhrase.h>
#import <AssistantServices/AFSpeechRequestOptions.h>
#import <AssistantServices/AFSpeechToken.h>
#import <AssistantServices/AFTimer.h>
#import <AssistantServices/AFUIApplicationSiriTaskDeliverer.h>
#import <AssistantServices/AFUpdateAlarmRequest.h>
#import <AssistantServices/AFUpdateAlarmResponse.h>
#import <AssistantServices/AFUpdateMessageRequest.h>
#import <AssistantServices/AFUserUtterance.h>
#import <AssistantServices/AFVoiceInfo.h>
#import <AssistantServices/AFWatchdogTimer.h>
#import <AssistantServices/AFXPCWrapper.h>
#import <AssistantServices/_AFSpeakableUtterancePassThroughProvider.h>
