// IDSFoundation.framework umbrella header
// Auto-generated from iOS 8.4.3 dyld_shared_cache (AppleTV 3,2)

#import <Foundation/Foundation.h>

#import <IDSFoundation/IDSAppleRegistrationKeychainReader.h>
#import <IDSFoundation/IDSBaseMessage.h>
#import <IDSFoundation/IDSBaseSocketPairConnection.h>
#import <IDSFoundation/IDSDelegateInfo.h>
#import <IDSFoundation/IDSFaceTimeServerBag.h>
#import <IDSFoundation/IDSMessage.h>
#import <IDSFoundation/IDSMessageContext.h>
#import <IDSFoundation/IDSMessageToDelete.h>
#import <IDSFoundation/IDSProtobuf.h>
#import <IDSFoundation/IDSPushHandler.h>
#import <IDSFoundation/IDSPushHandlerContext.h>
#import <IDSFoundation/IDSRemoteCredential.h>
#import <IDSFoundation/IDSRemoteURLConnection.h>
#import <IDSFoundation/IDSSendParameters.h>
#import <IDSFoundation/IDSServerBag.h>
#import <IDSFoundation/IDSSockAddrWrapper.h>
#import <IDSFoundation/IDSSocketPairAckMessage.h>
#import <IDSFoundation/IDSSocketPairAppAckMessage.h>
#import <IDSFoundation/IDSSocketPairAttachmentMessage.h>
#import <IDSFoundation/IDSSocketPairConnection.h>
#import <IDSFoundation/IDSSocketPairDataMessage.h>
#import <IDSFoundation/IDSSocketPairDeliveryReceipt.h>
#import <IDSFoundation/IDSSocketPairDictionaryMessage.h>
#import <IDSFoundation/IDSSocketPairEncryptedMessage.h>
#import <IDSFoundation/IDSSocketPairErrorMessage.h>
#import <IDSFoundation/IDSSocketPairExpiredAckMessage.h>
#import <IDSFoundation/IDSSocketPairFragmentedMessage.h>
#import <IDSFoundation/IDSSocketPairGenericCommandMessage.h>
#import <IDSFoundation/IDSSocketPairGenericGroupMessageCommand.h>
#import <IDSFoundation/IDSSocketPairHandshake.h>
#import <IDSFoundation/IDSSocketPairKeepAliveMessage.h>
#import <IDSFoundation/IDSSocketPairLocationShareOfferCommand.h>
#import <IDSFoundation/IDSSocketPairMessage.h>
#import <IDSFoundation/IDSSocketPairNAckMessage.h>
#import <IDSFoundation/IDSSocketPairOTREncryptedMessage.h>
#import <IDSFoundation/IDSSocketPairPlayedReceipt.h>
#import <IDSFoundation/IDSSocketPairProtobufMessage.h>
#import <IDSFoundation/IDSSocketPairProxyIncomingNiceMessage.h>
#import <IDSFoundation/IDSSocketPairProxyOutgoingNiceMessage.h>
#import <IDSFoundation/IDSSocketPairReadReceipt.h>
#import <IDSFoundation/IDSSocketPairReflectedDeliveryReceipt.h>
#import <IDSFoundation/IDSSocketPairResourceTransferMessage.h>
#import <IDSFoundation/IDSSocketPairResourceTransferReceiver.h>
#import <IDSFoundation/IDSSocketPairResourceTransferSender.h>
#import <IDSFoundation/IDSSocketPairSMSDeliveryReceipt.h>
#import <IDSFoundation/IDSSocketPairSMSDownloadOutgoing.h>
#import <IDSFoundation/IDSSocketPairSMSFailure.h>
#import <IDSFoundation/IDSSocketPairSMSOutgoing.h>
#import <IDSFoundation/IDSSocketPairSMSReadReceipt.h>
#import <IDSFoundation/IDSSocketPairSMSTextDownloadMessage.h>
#import <IDSFoundation/IDSSocketPairSMSTextMessage.h>
#import <IDSFoundation/IDSSocketPairSavedReceipt.h>
#import <IDSFoundation/IDSSocketPairSessionAcceptMessage.h>
#import <IDSFoundation/IDSSocketPairSessionCancelMessage.h>
#import <IDSFoundation/IDSSocketPairSessionDeclineMessage.h>
#import <IDSFoundation/IDSSocketPairSessionEndMessage.h>
#import <IDSFoundation/IDSSocketPairSessionInvitationMessage.h>
#import <IDSFoundation/IDSSocketPairSessionMessage.h>
#import <IDSFoundation/IDSSocketPairTextMessage.h>
#import <IDSFoundation/IDSiMessageServerBag.h>
